### ISSUE TITLE
Titles in Matches view

### ISSUE THREAD

**Issue by Joschbosch** [Joschbosch/kickertool#28]
The matches view doesn't have titles (one might not know what the tablenumber is).

**Comment by DanielCleemann** [comment]
Did something like that. Except column titles, I added an image for the table. The rest should be clear enough, I guess. Also changed the match view a bit. What do you think?

**Comment by Joschbosch** [comment]
Looks great! Maybe the score could be a bit biggger font and bold? 
And the tables with TBA are not aligned like the already assigned tables, maybe this could be done? (Also, TBA could be changed but I don't know to what german thing :D)

**Comment by Joschbosch** [comment]
Looks great! Maybe the score could be a bit biggger font and bold? 
And the tables with TBA are not aligned like the already assigned tables, maybe this could be done? (Also, TBA could be changed but I don't know to what german thing :D)
