### ISSUE TITLE
Anzahl absolvierter Runden

### ISSUE THREAD

**Issue by DanielCleemann** [Joschbosch/kickertool#6]
Hi,

kannst du mir im Backend noch ne Methode bereitstellen, von wo ich die Anzahl absolvierter Runden holen kann? Falls es das schon gibt, kannst du mir sagen, was ich aufrufen muss?

**Comment by Joschbosch** [comment]
Am tournament ist jetzt eine methode, um alle completeRounds zu holen (diese + die current sind alle runden). Reicht dir das?

**Comment by DanielCleemann** [comment]
Ja, das sollte reichen, ansonsten melde ich mich nochmal.
