### ISSUE TITLE
Vorherige Runden liefern keine Matches

### ISSUE THREAD

**Issue by DanielCleemann** [Joschbosch/kickertool#8]
Hi,

mir ist aufgefallen, dass die Methode getBackendController().getMatchesForRound(round) keine Matches für bereits absolvierte Runden liefert. Die Liste ist immer leer. Kannst du dir das einmal ansehen? Oder muss ich etwas dabei beachten?

Wenn du pullst, kannst du das selbst hier prüfen: FXMLTournamentController.fillMatchesForRound() Einfach mal zwei Runden spielen und dann über die Combobox eine vorherige Runde auswählen.

**Comment by Joschbosch** [comment]
sollte gefixt sein :)
